import Link from 'next/link';
import { ArrowRight, Check, Heart, ShieldCheck, Sparkles, Truck } from 'lucide-react';
import Navbar from '../components/Navbar';
import Footer from '../components/Footer';

const values = [
  { icon: Sparkles, title: 'Curated, not crowded', text: 'We focus on wearable menswear instead of filling the rack with unnecessary choices.' },
  { icon: ShieldCheck, title: 'Quality first', text: 'We look for fabrics, finishing and fits that feel worth wearing again and again.' },
  { icon: Heart, title: 'Customer-led style', text: 'Your feedback helps shape what we bring next — because your style comes first.' },
  { icon: Truck, title: 'Made easy', text: 'From local shopping to nationwide delivery, we want the buying experience to stay simple.' },
];

export default function AboutPage() {
  return <main className="min-h-screen bg-[#f4efe5]"><Navbar/>
    <section className="relative overflow-hidden bg-[#071725] text-white"><div className="absolute inset-0 opacity-35"><img src="/images/story.svg" alt="" className="h-full w-full object-cover"/></div><div className="absolute inset-0 bg-gradient-to-r from-[#071725] via-[#071725]/95 to-[#071725]/35"/><div className="container relative flex min-h-[570px] items-center py-20"><div className="max-w-3xl"><p className="text-xs font-bold tracking-[.32em] text-[#d4af6a]">ABOUT SOLO STATE</p><h1 className="serif mt-5 text-6xl leading-[.95] sm:text-7xl lg:text-[100px]">Define your attitude.</h1><p className="mt-7 max-w-2xl text-sm leading-7 text-white/65 sm:text-base">Solo State is a men&apos;s fashion brand built around one simple idea: your clothes should feel like an expression of who you are — not a costume.</p><Link href="/shop" className="gold-btn mt-9 inline-flex items-center gap-3 px-7 py-4 text-xs font-bold tracking-[.13em]">EXPLORE THE SHOP <ArrowRight size={16}/></Link></div></div></section>
    <section className="container grid gap-12 py-20 sm:py-24 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><p className="text-xs font-bold tracking-[.3em] text-[#a18348]">OUR STORY</p><h2 className="serif mt-4 text-4xl leading-tight sm:text-6xl">Style should be accessible, personal and worth remembering.</h2><p className="mt-7 text-sm leading-7 text-black/60 sm:text-base">We started Solo State with a focus on men who want to look sharp without making fashion complicated. Our collections balance modern silhouettes, familiar essentials and statement pieces — while keeping value at the heart of the experience.</p><p className="mt-5 text-sm leading-7 text-black/60 sm:text-base">Whether you walk into our showroom or shop online, the goal stays the same: make it easier to find something that feels right for you.</p></div><div className="overflow-hidden bg-[#071725] p-5 sm:p-8"><img src="/images/campaign.svg" alt="Solo State campaign" className="h-[380px] w-full object-cover"/></div></section>
    <section className="bg-white py-20 sm:py-24"><div className="container"><div className="mb-12 max-w-2xl"><p className="text-xs font-bold tracking-[.3em] text-[#a18348]">WHAT WE BELIEVE</p><h2 className="serif mt-4 text-4xl sm:text-5xl">The Solo State way.</h2></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{values.map(({icon:Icon,title,text})=><div key={title} className="border border-black/10 p-7"><Icon size={23} className="text-[#a18348]"/><h3 className="mt-6 text-lg font-semibold">{title}</h3><p className="mt-3 text-sm leading-6 text-black/55">{text}</p></div>)}</div></div></section>
    <section className="bg-[#071725] py-20 text-white sm:py-24"><div className="container grid gap-10 lg:grid-cols-2 lg:items-center"><div><p className="text-xs font-bold tracking-[.3em] text-[#d4af6a]">OUR PROMISE</p><h2 className="serif mt-4 text-4xl sm:text-6xl">Less noise. Better choices.</h2><p className="mt-6 max-w-xl text-sm leading-7 text-white/60">We want every visit to feel useful — discover something new, understand what you are buying, and leave with a piece you genuinely want to wear.</p></div><div className="space-y-4">{['Modern men’s fashion','Customer-friendly pricing','Nationwide delivery','Simple exchange support'].map(x=><div key={x} className="flex items-center gap-4 border-b border-white/10 pb-4"><span className="grid h-8 w-8 place-items-center rounded-full bg-[#d4af6a] text-black"><Check size={15}/></span><span>{x}</span></div>)}</div></div></section>
    <section className="container py-20 text-center"><p className="text-xs font-bold tracking-[.3em] text-[#a18348]">READY TO EXPLORE?</p><h2 className="serif mt-4 text-4xl sm:text-5xl">Find your next favourite piece.</h2><Link href="/collections" className="gold-btn mt-8 inline-flex items-center gap-3 px-8 py-4 text-xs font-bold tracking-[.13em]">EXPLORE COLLECTIONS <ArrowRight size={16}/></Link></section>
    <Footer/>
  </main>;
}
