"use client";
import { useMemo, useState } from 'react';
import ProductCard from '../shop-components/ProductCard';
import QuickAddModal from '../shop-components/QuickAddModal';
import SizeGuide from '../shop-components/SizeGuide';
import { Product, products } from '../shop-components/shop-data';

export default function NewArrivalsClient(){
 const [category,setCategory]=useState('All'); const [query,setQuery]=useState(''); const [wishlist,setWishlist]=useState<number[]>([]); const [quick,setQuick]=useState<Product|null>(null); const [sizeOpen,setSizeOpen]=useState(false); const categories=['All','T-Shirts','Shirts','Pants','Panjabi','Jackets','Accessories'];
 const items=useMemo(()=>products.filter(p=>(category==='All'||p.category===category)&&(`${p.name} ${p.category}`.toLowerCase().includes(query.toLowerCase()))).sort((a,b)=>b.id-a.id),[category,query]);
 return <section className="container py-14 sm:py-20"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-2 overflow-x-auto pb-1">{categories.map(c=><button key={c} onClick={()=>setCategory(c)} className={`shrink-0 border px-4 py-2 text-[10px] font-bold tracking-[.13em] ${category===c?'border-[#071725] bg-[#071725] text-white':'border-black/10 bg-white'}`}>{c}</button>)}</div><button onClick={()=>setSizeOpen(true)} className="text-xs font-bold underline underline-offset-4">Size Guide</button></div><div className="mt-6"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search new arrivals..." className="h-12 w-full border border-black/10 bg-white px-4 text-sm outline-none focus:border-[#071725]"/></div><div className="mt-10 flex items-center justify-between"><p className="text-xs text-black/45"><b className="text-black">{items.length}</b> new products</p><span className="text-[10px] font-bold uppercase tracking-[.15em] text-black/35">Latest first</span></div><div className="mt-7 grid grid-cols-2 gap-x-3 gap-y-7 sm:gap-x-5 md:grid-cols-3 xl:grid-cols-4">{items.map(p=><ProductCard key={p.id} product={p} wishlisted={wishlist.includes(p.id)} onWishlist={id=>setWishlist(x=>x.includes(id)?x.filter(i=>i!==id):[...x,id])} onQuickAdd={setQuick}/>)}</div>{!items.length&&<div className="py-24 text-center"><h2 className="serif text-3xl">No new arrivals found</h2><p className="mt-3 text-sm text-black/50">Try another category or search.</p></div>}{quick&&<QuickAddModal product={quick} onClose={()=>setQuick(null)} onAdded={()=>setQuick(null)}/>}<SizeGuide open={sizeOpen} onClose={()=>setSizeOpen(false)}/></section>;
}
