export type Product = {
  id: number;
  name: string;
  category: 'T-Shirts' | 'Shirts' | 'Pants' | 'Panjabi' | 'Jackets' | 'Accessories';
  price: number;
  oldPrice?: number;
  image: string;
  badge?: 'NEW' | 'BEST SELLER' | 'SALE' | 'POPULAR';
  colors: string[];
  sizes: string[];
  rating: number;
  reviews: number;
  stock: number;
};

export const products: Product[] = [
  {
    id: 1,
    name: 'Nebular Print T-Shirt',
    category: 'T-Shirts',
    price: 1490,
    oldPrice: 1690,
    image: '/images/tshirt.svg',
    badge: 'NEW',
    colors: ['Black', 'Navy', 'Cream'],
    sizes: ['M', 'L', 'XL'],
    rating: 4.8,
    reviews: 38,
    stock: 12,
  },
  {
    id: 2,
    name: 'Oxford Premium Shirt',
    category: 'Shirts',
    price: 2190,
    image: '/images/shirt.svg',
    badge: 'NEW',
    colors: ['White', 'Sky', 'Black'],
    sizes: ['M', 'L', 'XL'],
    rating: 4.9,
    reviews: 24,
    stock: 8,
  },
  {
    id: 3,
    name: 'Twill Formal Pants',
    category: 'Pants',
    price: 2230,
    oldPrice: 2790,
    image: '/images/pants.svg',
    badge: 'SALE',
    colors: ['Black', 'Charcoal', 'Navy'],
    sizes: ['30', '32', '34', '36'],
    rating: 4.7,
    reviews: 31,
    stock: 16,
  },
  {
    id: 4,
    name: 'Embroidered Panjabi',
    category: 'Panjabi',
    price: 2990,
    image: '/images/panjabi.svg',
    badge: 'POPULAR',
    colors: ['Cream', 'White', 'Black'],
    sizes: ['M', 'L', 'XL'],
    rating: 4.9,
    reviews: 52,
    stock: 5,
  },
  {
    id: 5,
    name: 'Urban Bomber Jacket',
    category: 'Jackets',
    price: 3990,
    oldPrice: 4990,
    image: '/images/jacket.svg',
    badge: 'SALE',
    colors: ['Black', 'Olive'],
    sizes: ['M', 'L', 'XL'],
    rating: 4.6,
    reviews: 19,
    stock: 4,
  },
  {
    id: 6,
    name: 'Minimal Steel Watch',
    category: 'Accessories',
    price: 1890,
    image: '/images/watch.svg',
    badge: 'BEST SELLER',
    colors: ['Steel', 'Black'],
    sizes: ['One Size'],
    rating: 4.8,
    reviews: 46,
    stock: 20,
  },
  {
    id: 7,
    name: 'Classic Heavyweight Tee',
    category: 'T-Shirts',
    price: 990,
    image: '/images/tshirt.svg',
    colors: ['White', 'Black', 'Olive'],
    sizes: ['M', 'L', 'XL'],
    rating: 4.6,
    reviews: 27,
    stock: 23,
  },
  {
    id: 8,
    name: 'Signature Oxford Shirt',
    category: 'Shirts',
    price: 2390,
    image: '/images/shirt.svg',
    colors: ['Navy', 'White'],
    sizes: ['M', 'L', 'XL'],
    rating: 4.7,
    reviews: 18,
    stock: 9,
  },
  {
    id: 9,
    name: 'Straight Fit Chino',
    category: 'Pants',
    price: 1990,
    image: '/images/pants.svg',
    colors: ['Beige', 'Black', 'Navy'],
    sizes: ['30', '32', '34', '36'],
    rating: 4.5,
    reviews: 22,
    stock: 14,
  },
  {
    id: 10,
    name: 'Classic Premium Panjabi',
    category: 'Panjabi',
    price: 2690,
    image: '/images/panjabi.svg',
    colors: ['White', 'Cream'],
    sizes: ['M', 'L', 'XL'],
    rating: 4.8,
    reviews: 35,
    stock: 11,
  },
  {
    id: 11,
    name: 'Midnight Bomber',
    category: 'Jackets',
    price: 4290,
    image: '/images/jacket.svg',
    badge: 'NEW',
    colors: ['Black', 'Navy'],
    sizes: ['M', 'L', 'XL'],
    rating: 4.7,
    reviews: 14,
    stock: 7,
  },
  {
    id: 12,
    name: 'Everyday Steel Watch',
    category: 'Accessories',
    price: 1590,
    image: '/images/watch.svg',
    colors: ['Steel', 'Black'],
    sizes: ['One Size'],
    rating: 4.5,
    reviews: 29,
    stock: 18,
  },
];

export const categories = [
  'All',
  'T-Shirts',
  'Shirts',
  'Pants',
  'Panjabi',
  'Jackets',
  'Accessories',
] as const;

export type Category = (typeof categories)[number];
